### ISSUE TITLE
Fails to start

### ISSUE THREAD

**Issue by benstadin** [digidem/mapeo-desktop#100]
Mapeo fails to start. I just checked out the latest master branch and followed the instructions. The error message is:

$ npm start

> mapeo-desktop@1.8.2 start /Users/user/dev/map/mapeo-desktop
> electron app.js --disable-http-cache

App threw an error during load
TypeError: Cannot read property 'presets' of null
    at Object.<anonymous> (/Users/user/dev/map/mapeo-desktop/lib/export-geojson.js:9:54)
    at Module._compile (module.js:541:32)
    at Object.Module._extensions..js (module.js:550:10)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/user/dev/map/mapeo-desktop/lib/menu.js:5:21)
    at Module._compile (module.js:541:32)
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0
[warn] kq_init: detected broken kqueue; not using.: Undefined error: 0

**Comment by noffle** [comment]
Thanks for the report @benstadin. This is happening because you have no presets loaded. Though it certainly should not crash! I pushed a fix for this in 1.8.3. Try pulling from master now and you should be able to run.

**Comment by benstadin** [comment]
Thanks, works for me now.
