### ISSUE TITLE
Updater error on Mac on master

### ISSUE THREAD

**Issue by gmaclennan** [digidem/mapeo-desktop#395]
I'm seeing a bunch of these errors when I open Mapeo on `master` on a Mac:

```
2020-08-17T16:05:51.407Z [main] error: [MAIN/IPC] error Error: Cannot find channel "latest-mac.yml" update info: HttpError: 404 
"method: GET url: https://downloads.mapeo.app/desktop/latest-mac.yml?noCache=1efuimtmv\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "status": "404",
  "date": "Mon, 17 Aug 2020 16:05:51 GMT",
  "content-type": "text/html; charset=utf-8",
  "set-cookie": [
    "__cfduid=d9e78ec045568b5edafbf6a0c250537921597680351; expires=Wed, 16-Sep-20 16:05:51 GMT; path=/; domain=.mapeo.app; HttpOnly; SameSite=Lax"
  ],
  "x-amz-request-id": "6CFBC503AF359D7D",
  "x-amz-id-2": "iSfJADGMhLU+r5TRJYGEm5Z9Mr3amRCqGr1SGzHRwumS2lGKjvHr49W0kXEdtRInhvnXT26oQlQ=",
  "cf-cache-status": "DYNAMIC",
  "cf-request-id": "049ec48f3f0000bbc4ab97d200000001",
  "expect-ct": "max-age=604800, report-uri=\"https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct\"",
  "server": "cloudflare",
  "cf-ray": "5c44a391fe27bbc4-LHR",
  "content-encoding": "br"
}
    at createHttpError (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:84:10)
    at ElectronHttpExecutor.handleResponse (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:169:14)
    at ClientRequest.<anonymous> (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/httpExecutor.js:134:16)
    at ClientRequest.emit (events.js:223:5)
    at ClientRequest.EventEmitter.emit (domain.js:475:20)
    at SimpleURLLoaderWrapper.<anonymous> (electron/js2c/browser_init.js:93:6152)
    at SimpleURLLoaderWrapper.emit (events.js:223:5)
    at SimpleURLLoaderWrapper.EventEmitter.emit (domain.js:475:20)
    at SimpleURLLoaderWrapper.topLevelDomainCallback (domain.js:130:23)
    at newError (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/node_modules/builder-util-runtime/out/index.js:212:17)
    at GenericProvider.getLatestVersion (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/out/providers/GenericProvider.js:60:52)
    at async MacUpdater.getUpdateInfoAndProvider (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:487:13)
    at async MacUpdater.doCheckForUpdates (…dist/mac/Mapeo.app/Contents/Resources/app.asar/node_modules/electron-updater/out/AppUpdater.js:503:20) {
  code: 'ERR_UPDATER_CHANNEL_FILE_NOT_FOUND'
}
```

**Comment by okdistribute** [comment]
This is showing up because we've never published a latest-mac.yml file because we've never published a latest release for Mapeo yet with the auto updater. So this is difficult to test in production unless we publish something. Perhaps I can manually publish an older version to `https://downloads.mapeo.app/desktop`

**Comment by gmaclennan** [comment]
Can we maybe put the [yaml files from v5.3.1](https://github.com/digidem/mapeo-desktop/releases/tag/v5.3.1) there, then we will stop getting the errors, and we will be able to test _some_ of the functionality (no newer releases)

**Comment by okdistribute** [comment]
OK Done!
