### ISSUE TITLE
Error: Module version mismatch - v1.2.9 macOS package

### ISSUE THREAD

**Issue by ungoldman** [digidem/mapeo-desktop#47]
When installing v1.2.9 via the packaged `dmg` on https://github.com/digidem/mapeo-desktop/releases/tag/v1.2.9, I get a version mismatch error.

I'm on a 2011 MBP running OS X 10.11.6 (El Capitan).

I'm guessing this is due to leveldb (or something like it) not getting rebuilt for electron at some point in the packaging & distribution process. Will try to help fix it when I get some time but thought I'd report it for now.

## error text

```
Uncaught Exception:
Error: Module version mismatch. Expected 49, got 48.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:167:20)
    at Object.Module._extensions..node (module.js:568:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:167:20)
    at Module.load (module.js:458:32)
    at tryModuleLoad (module.js:417:12)
    at Function.Module._load (module.js:409:3)
    at Module.require (module.js:468:17)
    at require (internal/module.js:20:19)
    at bindings (/Applications/Mapeo.app/Contents/Resources/app/node_modules/bindings/bindings.js:76:44)
```

## scrensho

![screen shot 2016-10-05 at 4 00 43 pm](https://cloud.githubusercontent.com/assets/427322/19134754/e2943440-8b14-11e6-81c3-74491eec4b10.png)

**Comment by gmaclennan** [comment]
Thanks for the report @ungoldman. @noffle has been rapidly iterating the build code, looks like `npm rebuild-leveldb` is not running, or is running with the wrong version of electron.

**Comment by noffle** [comment]
Thanks for the report @ungoldman! I'll do some digging.

**Comment by noffle** [comment]
You were right @ungoldman -- the leveldb rebuild wasn't happening. Thank you! :star2: 

Fixed in https://github.com/digidem/mapeo-desktop/releases/tag/v1.2.10
